### ISSUE TITLE
Bot CIs are Failing with permission issues

### ISSUE THREAD

**Issue by YJDoc2** [youki-dev/youki#2972]
See :
- https://github.com/youki-dev/youki/actions/runs/11622169941/job/32393990683
- https://github.com/youki-dev/youki/actions/runs/11631956938/job/32394142811

Both of these have failed with permission related errors. Given that both of these CI are important, dependabot takes care of patch updates and tagpr helps a lot with Changelog, we need to see what is the issue and fix it as soon as we can.

I suspect that after becoming the part of cncf org, there might be default restrictions on CI permissions, and we might need to grant the CI permissions explicitly to get them working again. Need to check and fix.

**Comment by utam0k** [comment]
I've given workflows read and write permissions.

**Comment by YJDoc2** [comment]
Verified, thanks!
