### ISSUE TITLE
Determine a benchmark comparison table format for the README

### ISSUE THREAD

**Issue by Dentrax** [youki-dev/youki#518]
This is a follow-up issue for #464, which we have to implement it in first place. Since that issue is about how to implement benchmarking method in right way, whereas this issue is about how can we visualize a fancy and simple _table_ in the README. Just dropping the idea here, so we do not forget!

@utam0k [measured](https://github.com/containers/youki/pull/447#issuecomment-958991982) the performance using the [hyperfine](https://github.com/sharkdp/hyperfine). Since hyperfine is really cool tool to measure benchmark, we can add some valuable information such as:
* **CPU:** _min, max, mean_
* **MEM**: _min, max, mean_

We can create many tables for each command:

| runtime | release |                                  cmd: create                                  | diff | winner |
|---------|---------|-------------------------------------------------------------------------------|------|--------|
| youki   | v1      | mem: (min: x, max: y), cpu: (min: x, max: y), time: (min: x, max: y, mean: z) | +%2  | youki  |
| runc    | v2      | mem: (min: x, max: y), cpu: (min: x, max: y), time: (min: x, max: y, mean: z) | +%3  | runc   |
| crun    | v3      | mem: (min: x, max: y), cpu: (min: x, max: y), time: (min: x, max: y, mean: z) | +%4  | crun   |

- **runtime:** _name of the runtime_
- **release:** _perma link to release tag or commit_
- **cmd:** _which command is tested_
- **diff:** _how fast compared to other ones_
- **winner:** _who won_

What do you think?

**Comment by utam0k** [comment]
@Dentrax 
Thanks for your interest!
This table is very cool. however, the `winner` column may be a bit extreme, so I think we remove it. As for the superiority, just looking at the numbers should be enough.

**Comment by YJDoc2** [comment]
I'm closing this, since we have a basic format in readme, and it has been useful till now. We can add fields as required, nothing particular to follow up in this issue anymore.
